### PR TITLE
Add ignoreList to the author type command

### PR DESCRIPTION
**Pull request by zoltanbedi**
I'd like to add an ignoreList argument to the author type so we can add bots to the list and the external pr command won't add label to them.

### CODE REVIEW

**Review by marefr — APPROVED** [review]
LGTM

Just wonder if we should always ignore bots and/or if we can do that. I know some users in GitHub is actually of type `Bot`. For example this one https://api.github.com/users/welcome[bot]. Grafanabot though is of type `User`, https://api.github.com/users/grafanabot. Something you've considered? Or filter out all users containing "bot"?

**Comment by zoltanbedi** [comment]
Hmm that’s a good question. I should check this first. I've seen that @daniellee is manually removing the external tag from the renovate bots prs and thought that we can do something about it. For example here https://github.com/grafana/grafana/pull/42473

**Comment by marefr** [comment]
@zoltanbedi hmm okay. Interestingly https://api.github.com/users/renovate doesn't say it's a bot. Looking at the PR it has this label bot:
image

How does GitHub know that?

**Comment by zoltanbedi** [comment]
yeah but there is renovate[bot] https://api.github.com/users/renovate%5Bbot%5D
it looks like that I need to change the pr because these bots do not have name fields filled out.

**Comment by marefr** [comment]
Sure go for it

**Pull request merged**
