### PR TITLE
Chore: Create new github action to update latest.json

### PR DESCRIPTION
**Pull request by papagian**
For grafana/grafana-release#75

### CODE REVIEW

**Comment by tolzhabayev** [comment]
@papagian (I might be totally wrong here):
- Doesn't it has to be a part of https://github.com/grafana/grafana-github-actions/blob/main/bump-version/action.yml
- + I thought the idea was to check that the version is > then the one in the file, otherwise prevent overwriting. See https://grafana.slack.com/archives/CSKQV9Y5B/p1638900764057400

**Comment by papagian** [comment]
> @papagian (I might be totally wrong here):
> 
> * Doesn't it has to be a part of https://github.com/grafana/grafana-github-actions/blob/main/bump-version/action.yml

I think they are different; `bump-version` is for updating frontend packages while this one is [for updating the `latest.json`](https://internal-ops-us-east-0.grafana.net/grafana-release-guide/v8.3.0/update-latestjson/)
> * And I thought the idea was to check that the version is `>` then the one in the `latest.json`, otherwise do nothing to prevent overwriting. See https://grafana.slack.com/archives/CSKQV9Y5B/p1638900764057400

👍

**Comment by hugohaggmark** [comment]
I think @papagian is  correct.

**Comment by tolzhabayev** [comment]
@papagian is this PR still relevant?

**Comment by papagian** [comment]
> @papagian is this PR still relevant?

I don't know. Maybe @grafana/grafana-release-eng knows better whether we need it or not

**Comment by dsotirakis** [comment]
@papagian, @tolzhabayev 👋 
I think it's still relevant, would be nice to have a github action to automatically create the latest.json PR.
Currently we have to create one manually and then backport to the versioned branch.

**Comment by tolzhabayev** [comment]
still relevant? @dsotirakis :)

**Comment by dsotirakis** [comment]
> still relevant? @dsotirakis :)

I think yes, but it'd look better in the `grafana/grafana-github-actions-go` repo. Let's close this one

**Pull request closed without merging**
